Họ và tên sinh viên : Phạm Ngọc Thịnh

# Bài tập về nhà: Singular Value Decomposition (SVD)

Bài tập gồm 2 câu:

1. Phân rã một ma trận có rank thấp bằng SVD.
2. Chọn số thành phần k cho Truncated SVD dựa trên tỷ lệ năng lượng.

---

# Câu 1. Phân rã ma trận

Cho ma trận:

$$
A=
\begin{bmatrix}
1 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
0 & 1 & 1
\end{bmatrix}
\in\mathbb{R}^{4\times3}
$$

### 1. Chứng minh các cột của $A$ phụ thuộc tuyến tính và xác định $\operatorname{rank}(A)$

- Đặt các cột của $A$ lần lượt là:
  $$
  c_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 0 \end{bmatrix}, \quad
  c_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \\ 1 \end{bmatrix}, \quad
  c_3 = \begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}
  $$
- Ta thấy $c_3 = c_1 + c_2$ ,Vì cột $c_3$ biểu diễn được qua  $c_1$ và $c_2$, nên các cột của ma trận $A$ phụ thuộc tuyến tính.
- Mặt khác, hai cột $c_1$ và $c_2$ độc lập tuyến tính với nhau . Do đó, số cột độc lập tuyến tính tối đa là 2, => $\operatorname{rank}(A) = 2$.

---

### 2. Tính $A^\top A$

- Ta có:
  $$
  A^\top A = 
  \begin{bmatrix}
  1 & 0 & 1 & 0\\
  0 & 1 & 0 & 1\\
  1 & 1 & 1 & 1
  \end{bmatrix}
  \begin{bmatrix}
  1 & 0 & 1\\
  0 & 1 & 1\\
  1 & 0 & 1\\
  0 & 1 & 1
  \end{bmatrix}
  $$
 =>
  $$
  A^\top A = 
  \begin{bmatrix}
  2 & 0 & 2\\
  0 & 2 & 2\\
  2 & 2 & 4
  \end{bmatrix}
  $$

---

### 3. Tìm các eigenvalues và eigenvectors trực chuẩn của $A^\top A$

- Lập phương trình đặc trưng $\det(A^\top A - \lambda I) = 0$:
  $$
  \det \begin{bmatrix}
  2-\lambda & 0 & 2\\
  0 & 2-\lambda & 2\\
  2 & 2 & 4-\lambda
  \end{bmatrix} = 0
  $$
- Khai triển định thức theo hàng thứ nhất:
  $$
  (2-\lambda) \cdot \left| \begin{matrix} 2-\lambda & 2 \\ 2 & 4-\lambda \end{matrix} \right| + 2 \cdot \left| \begin{matrix} 0 & 2-\lambda \\ 2 & 2 \end{matrix} \right| = 0
  $$

  $$
    <=>(2-\lambda)(\lambda^2 - 6\lambda + 4) + 2(-4 + 2\lambda) = 0
  $$
  $$
    <=>(2\lambda^2 - 12\lambda + 8 - \lambda^3 + 6\lambda^2 - 4\lambda) - 8 + 4\lambda = 0
  $$
  $$
    <=>-\lambda^3 + 8\lambda^2 - 12\lambda = 0 \implies -\lambda(\lambda^2 - 8\lambda + 12) = 0
  $$
  $$
    <=>-\lambda(\lambda - 2)(\lambda - 6) = 0
  $$
- Giải phương trình ta được các eigenvalues: $\lambda_1 = 6$, $\lambda_2 = 2$, $\lambda_3 = 0$.

- **Tìm eigenvector ứng với $\lambda_1 = 6$:** Giải hệ $(A^\top A - 6I)v_1 = 0$:
  $$
  \begin{bmatrix}
  2-6 & 0 & 2\\
  0 & 2-6 & 2\\
  2 & 2 & 4-6
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
  \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} \implies
  \begin{bmatrix}
  -4 & 0 & 2\\
  0 & -4 & 2\\
  2 & 2 & -2
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
  \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
  $$
  Từ phương trình 1 và 2, ta có: $4x_1 = 2x_3 \implies x_3 = 2x_1$ và $4x_2 = 2x_3 \implies x_3 = 2x_2 \implies x_1 = x_2$.
  Chọn $x_1 = 1 \implies x_2 = 1, x_3 = 2$. Vector riêng ban đầu: $\tilde{v}_1 = \begin{bmatrix} 1 & 1 & 2 \end{bmatrix}^\top$.  
  Chuẩn hóa vector này bằng cách chia cho độ dài $\|\tilde{v}_1\| = \sqrt{1^2 + 1^2 + 2^2} = \sqrt{6}$:
  $$
  v_1 = \begin{bmatrix} \frac{1}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} \\ \frac{2}{\sqrt{6}} \end{bmatrix}
  $$

- **Tìm eigenvector ứng với $\lambda_2 = 2$:** Giải hệ $(A^\top A - 2I)v_2 = 0$:
  $$
  \begin{bmatrix}
  2-2 & 0 & 2\\
  0 & 2-2 & 2\\
  2 & 2 & 4-2
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
  \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} \implies
  \begin{bmatrix}
  0 & 0 & 2\\
  0 & 0 & 2\\
  2 & 2 & 2
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
  \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
  $$
  Từ hai phương trình đầu ta có $2x_3 = 0 \implies x_3 = 0$. Thay vào phương trình 3: $2x_1 + 2x_2 + 2(0) = 0 \implies x_1 = -x_2$.
  Chọn $x_2 = 1 \implies x_1 = -1, x_3 = 0$. Vector riêng ban đầu: $\tilde{v}_2 = \begin{bmatrix} -1 & 1 & 0 \end{bmatrix}^\top$.
  Chuẩn hóa với $\|\tilde{v}_2\| = \sqrt{(-1)^2 + 1^2 + 0^2} = \sqrt{2}$:
  $$
  v_2 = \begin{bmatrix} -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ 0 \end{bmatrix}
  $$

- **Tìm eigenvector ứng với $\lambda_3 = 0$:** Giải hệ $(A^\top A - 0I)v_3 = 0$:
  $$
  \begin{bmatrix}
  2 & 0 & 2\\
  0 & 2 & 2\\
  2 & 2 & 4
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
  \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} \implies
  \begin{cases}
  2x_1 + 2x_3 = 0 \implies x_1 = -x_3 \\
  2x_2 + 2x_3 = 0 \implies x_2 = -x_3
  \end{cases}
  $$
  Chọn $x_3 = 1 \implies x_1 = -1, x_2 = -1$. Vector riêng ban đầu: $\tilde{v}_3 = \begin{bmatrix} -1 & -1 & 1 \end{bmatrix}^\top$.
  Chuẩn hóa với $\|\tilde{v}_3\| = \sqrt{(-1)^2 + (-1)^2 + 1^2} = \sqrt{3}$:
  $$
  v_3 = \begin{bmatrix} -\frac{1}{\sqrt{3}} \\ -\frac{1}{\sqrt{3}} \\ \frac{1}{\sqrt{3}} \end{bmatrix}
  $$

---

### 4. Sắp xếp $\lambda_1\geq\lambda_2\geq\lambda_3$

$$
\lambda_1 = 6, \quad \lambda_2 = 2, \quad \lambda_3 = 0
$$

---

### 5. Tính các singular values $\sigma_i=\sqrt{\lambda_i}$

$$
\sigma_1 = \sqrt{6}, \quad \sigma_2 = \sqrt{2}, \quad \sigma_3 = \sqrt{0} = 0
$$

---

### 6. Xác định các right singular vectors $v_1,v_2,v_3$

Lấy kết quả từ các vector riêng đã tìm và trực chuẩn hóa ở Câu 3:
$$
v_1 = \begin{bmatrix} \frac{1}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} \\ \frac{2}{\sqrt{6}} \end{bmatrix}, \quad
v_2 = \begin{bmatrix} -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ 0 \end{bmatrix}, \quad
v_3 = \begin{bmatrix} -\frac{1}{\sqrt{3}} \\ -\frac{1}{\sqrt{3}} \\ \frac{1}{\sqrt{3}} \end{bmatrix}
$$

---

### 7. Với mỗi $\sigma_i>0$, tính $u_i=Av_i/\sigma_i$

- **Với $\sigma_1 = \sqrt{6}$:**
  $$
  A v_1 = \begin{bmatrix} 1 & 0 & 1\\ 0 & 1 & 1\\ 1 & 0 & 1\\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} \\ \frac{2}{\sqrt{6}} \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{6}} + \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} + \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} + \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{6}} + \frac{2}{\sqrt{6}} \end{bmatrix} = \begin{bmatrix} \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \end{bmatrix}
  $$
  =>
  $$
  u_1 = \frac{1}{\sqrt{6}} \begin{bmatrix} \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \\ \frac{3}{\sqrt{6}} \end{bmatrix} = \begin{bmatrix} \frac{3}{6} \\ \frac{3}{6} \\ \frac{3}{6} \\ \frac{3}{6} \end{bmatrix} = \begin{bmatrix} \frac{1}{2} \\ \frac{1}{2} \\ \frac{1}{2} \\ \frac{1}{2} \end{bmatrix}
  $$

- **Với $\sigma_2 = \sqrt{2}$:**
  $$
  A v_2 = \begin{bmatrix} 1 & 0 & 1\\ 0 & 1 & 1\\ 1 & 0 & 1\\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ 0 \end{bmatrix} = \begin{bmatrix} -\frac{1}{\sqrt{2}} + 0 \\ 0 + \frac{1}{\sqrt{2}} \\ -\frac{1}{\sqrt{2}} + 0 \\ 0 + \frac{1}{\sqrt{2}} \end{bmatrix} = \begin{bmatrix} -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \end{bmatrix}
  $$
  =>
  $$
  u_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \end{bmatrix} = \begin{bmatrix} -\frac{1}{2} \\ \frac{1}{2} \\ -\frac{1}{2} \\ \frac{1}{2} \end{bmatrix}
  $$

---

### 8. Bổ sung các vector trực chuẩn còn thiếu (Full SVD)

Để tạo ma trận trực chuẩn $U \in \mathbb{R}^{4\times 4}$, ta cần tìm thêm hai vector $u_3$ và $u_4$ sao cho chúng trực giao với cả $u_1, u_2$ đồng thời trực chuẩn với nhau. 

Giả sử vector cần tìm có dạng tổng quát $x = (x_1, x_2, x_3, x_4)^\top$. Từ điều kiện trực giao với $u_1$ và $u_2$:
- $x \perp u_1 \iff \frac{1}{2}x_1 + \frac{1}{2}x_2 + \frac{1}{2}x_3 + \frac{1}{2}x_4 = 0 \iff x_1 + x_2 + x_3 + x_4 = 0$
- $x \perp u_2 \iff -\frac{1}{2}x_1 + \frac{1}{2}x_2 - \frac{1}{2}x_3 + \frac{1}{2}x_4 = 0 \iff -x_1 + x_2 - x_3 + x_4 = 0$

Cộng và trừ hai phương trình trên, ta được :
$$
\begin{cases} 
x_2 + x_4 = 0 \implies x_4 = -x_2 \\ 
x_1 + x_3 = 0 \implies x_3 = -x_1 
\end{cases}
$$

Do đó, tập hợp các vector thỏa mãn có dạng $x = (x_1, x_2, -x_1, -x_2)^\top = x_1(1, 0, -1, 0)^\top + x_2(0, 1, 0, -1)^\top$. Chọn các vector cơ sở độc lập và chuẩn hóa độ dài về 1, ta được hai vector bổ sung:
- $u_3 = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & 0 & -1 & 0 \end{bmatrix}^\top$
- $u_4 = \frac{1}{\sqrt{2}}\begin{bmatrix} 0 & 1 & 0 & -1 \end{bmatrix}^\top$

Từ đây, ta được Full SVD ($A = U\Sigma V^\top$) với các ma trận thành phần:
$$
U = 
\begin{bmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & \frac{1}{\sqrt{2}} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix}, \quad
\Sigma = 
\begin{bmatrix}
\sqrt{6} & 0 & 0 \\
0 & \sqrt{2} & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}, \quad
V^\top = 
\begin{bmatrix}
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}}
\end{bmatrix}
$$[cite: 3]

---

### 9. Reduced SVD

Ta có: $A = U_r\Sigma_rV_r^\top$ với $r = \operatorname{rank}(A) = 2$.
=>

$$
U_r = 
\begin{bmatrix}
\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}
\end{bmatrix} \in \mathbb{R}^{4\times 2}, \quad
\Sigma_r = 
\begin{bmatrix}
\sqrt{6} & 0 \\
0 & \sqrt{2}
\end{bmatrix} \in \mathbb{R}^{2\times 2}, \quad
V_r^\top = 
\begin{bmatrix}
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0
\end{bmatrix} \in \mathbb{R}^{2\times 3}
$$

Do đó:

$$
A = 
\begin{bmatrix}
\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}
\end{bmatrix}
\begin{bmatrix}
\sqrt{6} & 0 \\
0 & \sqrt{2}
\end{bmatrix}
\begin{bmatrix}
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0
\end{bmatrix}
$$

---
## 10. Kích thước và cấu trúc các ma trận trong Reduced SVD
Vì $r = 2$, kích thước của các ma trận thu gọn là:
- Ma trận $U_r \in \mathbb{R}^{4\times 2}$ chứa 2 cột đầu tiên của $U$:
  $$
  U_r = \begin{bmatrix} \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} \end{bmatrix}
  $$
- Ma trận đường chéo $\Sigma_r \in \mathbb{R}^{2\times 2}$ chứa các singular values dương:
  $$
  \Sigma_r = \begin{bmatrix} \sqrt{6} & 0 \\ 0 & \sqrt{2} \end{bmatrix}
  $$
- Ma trận chuyển vị $V_r^\top \in \mathbb{R}^{2\times 3}$ chứa 2 hàng đầu tiên của $V^\top$:
  $$
  V_r^\top = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \end{bmatrix}
  $$

---
### 11. Kiểm tra tính trực chuẩn 

Ta có: 

$$
U^\top U = 
\begin{bmatrix}
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}} & 0 \\
0 & \frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix}
\begin{bmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & \frac{1}{\sqrt{2}} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
= I
$$

và

$$
V^\top V = 
\begin{bmatrix}
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}}
\end{bmatrix}
\begin{bmatrix}
\frac{1}{\sqrt{6}} & -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\
\frac{2}{\sqrt{6}} & 0 & -\frac{1}{\sqrt{3}}
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
= I
$$

và

$$
U\Sigma V^\top = 
\begin{bmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & \frac{1}{\sqrt{2}} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{\sqrt{2}} & 0 \\
\frac{1}{2} & \frac{1}{2} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix}
\begin{bmatrix}
\sqrt{6} & 0 & 0 \\
0 & \sqrt{2} & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \\
\frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}}
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 1 \\
1 & 0 & 1 \\
0 & 1 & 1
\end{bmatrix}
= A
$$
---
### 12. Giải thích

- **Vì sao có một singular value bằng 0?** 
  Vì $\operatorname{rank}(A) = 2$, trong khi ma trận $A$ có 3 cột, nghĩa là không gian cột chỉ có số chiều tối đa là 2. Giá trị singular value thứ 3 ứng với chiều dư thừa bằng 0 ($\sigma_3 = 0$).
- **Singular vector tương ứng với singular value bằng 0 liên hệ thế nào với null space của $A$?** 
  Vector $v_3$ tương ứng với $\sigma_3 = 0$ nằm trong không gian triệt tiêu (null space) của $A$, thỏa mãn hệ thức $Av_3 = 0$.
- **Vì sao Reduced SVD vẫn tái tạo chính xác $A$?** 
  Vì các thành phần mở rộng ứng với singular value bằng 0 bị nhân với trọng số 0 trong ma trận $\Sigma$, việc lược bỏ chúng không làm thay đổi giá trị tổng của tích ma trận.

---

# Câu 2. Chọn k cho Truncated SVD bằng tỷ lệ năng lượng

Một ma trận dữ liệu $X$ có các singular values:

$$
\sigma_1=12,\qquad
\sigma_2=5,\qquad
\sigma_3=3,\qquad
\sigma_4=1
$$

### 1. Xác định rank của $X$

- Số lượng singular values lớn hơn 0 là 4 ($\sigma_1=12, \sigma_2=5, \sigma_3=3, \sigma_4=1$), do đó $\operatorname{rank}(X) = 4$.

---

### 2. Tính tổng năng lượng

$$
E_{\text{total}} = \sum_{i=1}^{4}\sigma_i^2 = 12^2 + 5^2 + 3^2 + 1^2
$$
$$
E_{\text{total}} = 144 + 25 + 9 + 1 = 179
$$

---

### 3. Với $k=1,2,3,4$, tính tỷ lệ $R(k)$

Công thức tổng quát:
$$
R(k) = \frac{\sum_{i=1}^{k}\sigma_i^2}{E_{\text{total}}} = \frac{\sum_{i=1}^{k}\sigma_i^2}{179}
$$

- Với $k = 1$:
  $$
  R(1) = \frac{12^2}{179} = \frac{144}{179} \approx 0.80446 \approx 80.45\%
  $$
- Với $k = 2$:
  $$
  R(2) = \frac{12^2 + 5^2}{179} = \frac{169}{179} \approx 0.94413 \approx 94.41\%
  $$
- Với $k = 3$:
  $$
  R(3) = \frac{12^2 + 5^2 + 3^2}{179} = \frac{178}{179} \approx 0.99441 \approx 99.44\%
  $$
- Với $k = 4$:
  $$
  R(4) = \frac{12^2 + 5^2 + 3^2 + 1^2}{179} = \frac{179}{179} = 1.00000 = 100.00\%
  $$

---

### 4. Hoàn thành bảng

| $k$ | Năng lượng giữ lại | Tỷ lệ $R(k)$ |
|---:|---:|---:|
| 1 | 144 | 80.45% |
| 2 | 169 | 94.41% |
| 3 | 178 | 99.44% |
| 4 | 179 | 100.00% |

---

### 5. Tìm $k$ nhỏ nhất để giữ ít nhất các mức năng lượng

- **80% năng lượng:** $k = 1$ (vì $R(1) \approx 80.45\% \geq 80\%$)
- **90% năng lượng:** $k = 2$ (vì $R(2) \approx 94.41\% \geq 90\%$)
- **95% năng lượng:** $k = 3$ (vì $R(3) \approx 99.44\% \geq 95\%$)
- **99% năng lượng:** $k = 3$ (vì $R(3) \approx 99.44\% \geq 99\%$)

---

### 6. Với $k=1,2,3$, tính $\|X-X_k\|_F$

Công thức: 
$$
\|X-X_k\|_F = \sqrt{\sum_{i=k+1}^{4}\sigma_i^2}
$$

- **Với $k = 1$:**
  $$
  \|X-X_1\|_F = \sqrt{\sigma_2^2 + \sigma_3^2 + \sigma_4^2} = \sqrt{5^2 + 3^2 + 1^2} = \sqrt{35} \approx 5.916
  $$
- **Với $k = 2$:**
  $$
  \|X-X_2\|_F = \sqrt{\sigma_3^2 + \sigma_4^2} = \sqrt{3^2 + 1^2} = \sqrt{10} \approx 3.162
  $$
- **Với $k = 3$:**
  $$
  \|X-X_3\|_F = \sqrt{\sigma_4^2} = \sqrt{1^2} = 1
  $$

---

### 7. Hoàn thành bảng

| $k$ | $R(k)$ | $\|X-X_k\|_F$ |
|---:|---:|---:|
| 1 | 80.45% | 5.916 |
| 2 | 94.41% | 3.162 |
| 3 | 99.44% | 1.000 |

---

### 8. Giả sử $\sigma_4$ chủ yếu biểu diễn nhiễu. Chọn $k$ phù hợp và giải thích

- **Lựa chọn:** Chọn $k = 3$.
- **Giải thích:** Vì $\sigma_4 = 1$ có giá trị rất nhỏ và được giả định là thành phần nhiễu trong dữ liệu, việc cắt cụt tại $k=3$ giúp loại bỏ nhiễu, làm sạch ma trận dữ liệu mà vẫn giữ lại được tới $99.44\%$ năng lượng quan trọng của hệ thống.

---

### 9. Trả lời các câu hỏi lý thuyết

- **Vì sao singular values phải được sắp xếp giảm dần?** 
  Sự sắp xếp giảm dần ($\sigma_1 \geq \sigma_2 \geq \dots \geq \sigma_n$) phản ánh mức độ quan trọng giảm dần của các thành phần đặc trưng (hay năng lượng) đóng góp vào ma trận dữ liệu, giúp việc chọn lựa cắt cụt ở $k$ tối ưu nhất.
- **Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?** 
  Không, vì các singular values nhỏ thường mang theo nhiễu hoặc thông tin không đáng kể. Giữ tất cả sẽ làm giảm hiệu suất nén và giữ lại cả nhiễu.
- **Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu là gì?** 
  Giữ năng lượng cao đòi hỏi chọn $k$ lớn, dẫn đến kích thước ma trận lớn và giảm mức độ nén; ngược lại, chọn $k$ nhỏ tăng mức độ nén dữ liệu nhưng làm mất mát nhiều thông tin gốc.

Kiếm tra lại bằng code

In [1]:
import numpy as np
# CÂU 1
A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)
# tính rank(A)
rank_A = np.linalg.matrix_rank(A)
print(f"Rank của A: {rank_A}")

# tính SVD của A
U, S, Vt = np.linalg.svd(A, full_matrices=True)

print("\nKẾT QUẢ SVD")
print(f"Singular values (S): {S}")
print(f"Kích thước U: {U.shape}")
print(f"Kích thước S (sigma): {S.shape}")
print(f"Kích thước Vt: {Vt.shape}")

#Kiểm tra tính trực chuẩn: U^T * U = I và V * V^T = I
print(f"\nU^T * U : \n{np.round(U.T @ U, 3)}")
print(f"Vt * Vt^T : \n{np.round(Vt @ Vt.T, 3)}")

# Tái tạo lại ma trận A từ U, S, Vt
Sigma_full = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma_full, S)
A_reconstructed = U @ Sigma_full @ Vt
print(f"\nkết quả tái tạo lại A có khớp với ban đầu? {np.allclose(A, A_reconstructed)}")

#CÂU 2
sigma = np.array([12, 5, 3, 1])
E_total = np.sum(sigma**2)
print(f"Tổng năng lượng E_total = {E_total}")

for k in range(1, 5):
    energy_k = np.sum(sigma[:k]**2)
    R_k = energy_k / E_total
    frobenius_diff = np.sqrt(np.sum(sigma[k:]**2))
    print(f"k = {k}: R(k) = {R_k*100:.2f}%, ||X - X_k||_F = {frobenius_diff:.3f}")

Rank của A: 2

KẾT QUẢ SVD
Singular values (S): [2.44948974 1.41421356 0.        ]
Kích thước U: (4, 4)
Kích thước S (sigma): (3,)
Kích thước Vt: (3, 3)

U^T * U : 
[[ 1.  0. -0. -0.]
 [ 0.  1.  0. -0.]
 [-0.  0.  1.  0.]
 [-0. -0.  0.  1.]]
Vt * Vt^T : 
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]

kết quả tái tạo lại A có khớp với ban đầu? True
Tổng năng lượng E_total = 179
k = 1: R(k) = 80.45%, ||X - X_k||_F = 5.916
k = 2: R(k) = 94.41%, ||X - X_k||_F = 3.162
k = 3: R(k) = 99.44%, ||X - X_k||_F = 1.000
k = 4: R(k) = 100.00%, ||X - X_k||_F = 0.000
